CREATE TABLE exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day VARCHAR(255) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room_enum VARCHAR(255) NOT NULL,
    CHECK (start_time < end_time)
);