CREATE TABLE blocks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    max_points DOUBLE PRECISION NOT NULL CHECK (max_points > 0),
    required_points DOUBLE PRECISION NOT NULL CHECK (required_points >= 0),
    CHECK (required_points <= max_points)
);