CREATE TABLE student_exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    exercise_id INTEGER NOT NULL,
    CONSTRAINT uq_student
        UNIQUE (student_id),
    CONSTRAINT fk_student
        FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_exercise
        FOREIGN KEY (exercise_id) REFERENCES exercises (id)
);
