CREATE TABLE exercise_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id INTEGER NOT NULL,
    session_date DATE NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by INTEGER,
    updated_at TIMESTAMP,
    CONSTRAINT uq_exercise_session_date
        UNIQUE (exercise_id, session_date),
    CONSTRAINT fk_exercise
        FOREIGN KEY (exercise_id) REFERENCES exercises (id),
    CONSTRAINT fk_created_by
        FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_updated_by
        FOREIGN KEY (updated_by) REFERENCES users (id)
);
