CREATE TABLE student_attendances (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    exercise_session_id INTEGER NOT NULL,
    attendance_enum VARCHAR(255) NOT NULL CHECK (attendance_enum IN ('PRESENT', 'ABSENT', 'SUBSTITUTED', 'EXCUSED')),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by INTEGER,
    updated_at TIMESTAMP,
    CONSTRAINT uq_exercise_session_student
        UNIQUE (exercise_session_id, student_id),
    CONSTRAINT fk_student
        FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_exercise_session
         FOREIGN KEY (exercise_session_id) REFERENCES exercise_sessions (id),
    CONSTRAINT fk_created_by
         FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_updated_by
         FOREIGN KEY (updated_by) REFERENCES users (id)
);