CREATE TABLE user_exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    exercise_id INTEGER NOT NULL,
    CONSTRAINT uq_user_exercise
        UNIQUE (user_id, exercise_id),
    CONSTRAINT fk_user
        FOREIGN KEY (user_id) REFERENCES users (id) /*ON DELETE CASCADE*/,
    CONSTRAINT fk_exercise
        FOREIGN KEY (exercise_id) REFERENCES exercises (id) --ON DELETE CASCADE
);
