CREATE TABLE student_assignment_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_assignment_id INTEGER NOT NULL,
    original_points DOUBLE PRECISION NOT NULL,
    updated_points DOUBLE PRECISION NOT NULL,
    original_user_id INTEGER NOT NULL,
    updated_by_user_id INTEGER NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_student_assignment
        FOREIGN KEY (student_assignment_id) REFERENCES student_assignments (id),
    CONSTRAINT fk_original_user
        FOREIGN KEY (original_user_id) REFERENCES users (id),
    CONSTRAINT fk_updated_by_user
        FOREIGN KEY (updated_by_user_id) REFERENCES users (id)
);
